DEBUG = True

USERNAME = 'root'
PASSWORD = '200410.'
SERVER = 'localhost'
DB = 'mmesa_db'

SQLALCHEMY_DATABASE_URI = f'mysql://{USERNAME}:{PASSWORD}@{SERVER}/{DB}'
SQLALCHEMY_TRACK_MODIFICATIONS = True