"""empty message

Revision ID: 1eee1d045905
Revises: 85b919c5c965
Create Date: 2023-12-29 00:06:02.777838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1eee1d045905'
down_revision = '85b919c5c965'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipamento',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('manufacturer', sa.String(length=100), nullable=False),
    sa.Column('equipment_type_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('problem_description', sa.String(length=1000), nullable=False),
    sa.Column('input_date', sa.Date(), nullable=False),
    sa.Column('output_date', sa.Date(), nullable=False),
    sa.Column('repair_description', sa.String(length=1000), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('equipamento')
    # ### end Alembic commands ###
