"""empty message

Revision ID: 41de29b3ca1a
Revises: 1eee1d045905
Create Date: 2023-12-29 15:05:58.855220

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '41de29b3ca1a'
down_revision = '1eee1d045905'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipamento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=True))
        batch_op.alter_column('equipment_type_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'cliente', ['owner_id'], ['id'])
        batch_op.create_foreign_key(None, 'tipo_equipamento', ['equipment_type_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipamento', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('equipment_type_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.drop_column('owner_id')

    # ### end Alembic commands ###
